secrets:
    password: ""

variables:
    channels: !!seq
        - "##TheChosenEvilOne"
        - "##lazy-valoran"
    server: irc.freenode.net
    nickname: TheChosenEvilBot
    prefix: "<<"
    realname: "bot"
    autoload: !!seq
        - "YAML/Base.yaml"
